import { createBlock } from "./studio.model";
import type { StudioBlock } from "./studio.types";

export interface StudioPreset { name: string; description: string; category: "section" | "marketplace"; featured?: boolean; create: () => StudioBlock[] }
const group = (name: string, blocks: StudioBlock[]) => blocks.map((block) => ({ ...block, group: name }));
export const studioPresets: StudioPreset[] = [
  { name: "Hero", description: "Centered greeting and intro", category: "section", create: () => group("Hero", [createBlock("heading", { content: "Hi, I'm {username} 👋", align: "center" }), createBlock("paragraph", { content: "I turn ideas into reliable software.", align: "center" })]) },
  { name: "About Me", description: "Personal summary and current focus", category: "section", create: () => group("About Me", [createBlock("heading", { content: "About me" }), createBlock("markdown", { content: "- 🔭 Currently building something useful\n- 🌱 Learning and sharing every day\n- 💬 Ask me about the web" })]) },
  { name: "Tech Stack", description: "Editable technology badges", category: "section", create: () => group("Tech Stack", [createBlock("heading", { content: "Tech stack" }), ...["TypeScript", "React", "Node.js"].map((name) => createBlock("badge", { title: name, url: `https://img.shields.io/badge/${encodeURIComponent(name)}-18181b?style=flat-square`, align: "center" }))]) },
  { name: "Stats", description: "Overview and language cards", category: "section", create: () => group("Stats", [createBlock("heading", { content: "GitHub stats" }), createBlock("card", { cardType: "overview", align: "center" }), createBlock("card", { cardType: "languages", title: "Languages", align: "center" })]) },
  { name: "Projects", description: "Projects heading and repository cards", category: "section", create: () => group("Projects", [createBlock("heading", { content: "Featured projects" }), createBlock("card", { cardType: "repository", title: "Repository", align: "center" })]) },
  { name: "Pinned", description: "Pinned repositories section", category: "section", create: () => group("Pinned", [createBlock("heading", { content: "Pinned work" }), createBlock("card", { cardType: "pinned", title: "Pinned repositories", align: "center" })]) },
  { name: "Achievements", description: "Contribution activity and streak", category: "section", create: () => group("Achievements", [createBlock("heading", { content: "Activity" }), createBlock("card", { cardType: "contributions", title: "Contributions", align: "center" }), createBlock("card", { cardType: "streak", title: "Streak", align: "center" })]) },
  { name: "Contact", description: "Social and contact links", category: "section", create: () => group("Contact", [createBlock("heading", { content: "Let's connect" }), createBlock("social", { align: "center" })]) },
  { name: "Support", description: "Sponsor placeholder", category: "section", create: () => group("Support", [createBlock("heading", { content: "Support my work" }), createBlock("badge", { title: "Buy Me a Coffee", url: "https://img.shields.io/badge/Buy_Me_A_Coffee-placeholder-FFDD00?logo=buymeacoffee&logoColor=black", align: "center" })]) },
  { name: "Footer", description: "Visitors and closing divider", category: "section", create: () => group("Footer", [createBlock("divider"), createBlock("visitors", { align: "center" })]) },
  { name: "Community Spotlight", description: "Local marketplace preview", category: "marketplace", featured: true, create: () => group("Community Spotlight", [createBlock("heading", { content: "Open source & community" }), createBlock("card", { cardType: "contributions", align: "center" })]) },
];
