import type { Metadata } from "next";
import Link from "next/link";
import { Menu, Search } from "lucide-react";
import { Card } from "@/components/ui/primitives";

export const metadata: Metadata = { title: "Documentation", description: "Embed and configure RepoPulse GitHub overview cards." };
const sections = ["Quick Start", "Overview Card", "Query Parameters", "Themes", "Caching", "Rate Limits", "Error Responses"];
const endpoint = "https://repopulse.kubik.gr/api/cards/overview?username=dimitrisnimas";

export default function Docs() {
  return <div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="mb-8 flex items-center gap-3 lg:hidden"><button aria-label="Open documentation navigation" className="rounded-lg border border-white/10 p-2"><Menu size={18} /></button><span className="text-sm text-zinc-400">Documentation</span></div><div className="grid gap-12 lg:grid-cols-[220px_minmax(0,1fr)_180px]">
    <aside className="hidden lg:block"><div className="sticky top-24"><p className="mb-4 text-xs font-medium uppercase tracking-wider text-zinc-600">Overview card</p><nav className="space-y-1">{sections.map((item, index) => <a key={item} href={`#${slug(item)}`} className={`block rounded-md px-3 py-2 text-sm ${index === 0 ? "bg-white/[.06] text-white" : "text-zinc-500 hover:text-white"}`}>{item}</a>)}</nav></div></aside>
    <article className="min-w-0"><label className="mb-10 flex h-11 items-center gap-3 rounded-lg border border-white/10 bg-white/[.025] px-3"><Search size={15} className="text-zinc-600" /><input className="w-full bg-transparent text-sm outline-none placeholder:text-zinc-600" placeholder="Search documentation..." aria-label="Search documentation" /><kbd className="text-xs text-zinc-700">⌘K</kbd></label>
      <p className="text-sm text-violet-300">Public API · v1</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Overview Card</h1><p className="mt-5 text-lg leading-8 text-zinc-400">A live SVG summary of any public GitHub profile—free, configurable, and ready for your README.</p>
      <Section id="quick-start" title="Quick Start"><p>Add this Markdown anywhere in your GitHub README:</p><Code>{`![RepoPulse GitHub Stats](${endpoint})`}</Code><p>Replace <Inline>dimitrisnimas</Inline> with a valid public GitHub username.</p></Section>
      <Section id="overview-card" title="Overview Card"><p>The card includes contributions, public repositories, stars, forks, pull requests, commits, followers, and the top languages calculated across all owned public repositories.</p><Code>{endpoint}</Code></Section>
      <Section id="query-parameters" title="Query Parameters"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-zinc-300"><tr><th className="pb-3">Parameter</th><th className="pb-3">Values</th><th className="pb-3">Default</th></tr></thead><tbody className="text-zinc-500">{[["username","GitHub username","required"],["theme","dark, light, github-dark, github-light, midnight","dark"],["width","320–900","480"],["show_avatar","true / false","false"],["show_icons","true / false","true"],["hide_border","true / false","false"],["hide","comma-separated metric names","—"],["locale","en, el, de, fr, es, it, pt, ja","en"]].map((row) => <tr key={row[0]} className="border-t border-white/[.07]"><td className="py-3 pr-4 font-mono text-xs text-violet-200">{row[0]}</td><td className="py-3 pr-4">{row[1]}</td><td className="py-3">{row[2]}</td></tr>)}</tbody></table></div><Code>{`${endpoint}&theme=github-dark&width=520&show_avatar=true`}</Code></Section>
      <Section id="themes" title="Themes"><p>Use <Inline>dark</Inline>, <Inline>light</Inline>, <Inline>github-dark</Inline>, <Inline>github-light</Inline>, or <Inline>midnight</Inline>. Unknown theme names safely fall back to dark.</p></Section>
      <Section id="caching" title="Caching behavior"><p>Rendered SVG cards are cached for reliability and speed. Responses are fresh for approximately one hour and may be served from stale cache for up to 24 hours when GitHub is temporarily unavailable. GitHub also caches README images, so changes may not appear instantly.</p></Section>
      <Section id="rate-limits" title="Rate limits"><p>Uncached public requests are initially limited to 60 per minute per source. Cached cards have minimal impact on this limit. A limited request returns an SVG card and a <Inline>Retry-After</Inline> header.</p></Section>
      <Section id="error-responses" title="Error responses"><p>Invalid usernames, missing users, upstream outages, and rate limits always return a safe standalone SVG—never internal details, stack traces, or credentials.</p></Section>
      <div className="mt-14 flex justify-between border-t border-white/[.08] pt-8 text-sm"><Link href="/" className="text-zinc-500 hover:text-white">← Home</Link><Link href="/playground" className="text-violet-300 hover:text-violet-200">Open Playground →</Link></div>
    </article>
    <aside className="hidden xl:block"><div className="sticky top-24 border-l border-white/10 pl-5"><p className="text-xs font-medium text-zinc-400">On this page</p>{sections.map((item) => <a key={item} href={`#${slug(item)}`} className="mt-3 block text-xs text-zinc-600 hover:text-white">{item}</a>)}</div></aside>
  </div></div>;
}
function slug(value: string) { return value.toLowerCase().replaceAll(" ", "-"); }
function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-24 border-t border-white/[.08] pt-10 first:mt-10"><h2 className="text-2xl font-semibold">{title}</h2><div className="mt-4 space-y-4 leading-7 text-zinc-500">{children}</div></section>; }
function Code({ children }: { children: string }) { return <Card className="my-5 overflow-x-auto p-4"><code className="whitespace-nowrap font-mono text-xs text-violet-200">{children}</code></Card>; }
function Inline({ children }: { children: React.ReactNode }) { return <code className="rounded bg-white/[.06] px-1.5 py-0.5 text-sm text-zinc-300">{children}</code>; }
