import { resolveTheme } from "@/config/themes";
import { svgDocument } from "@/server/cards/card-renderer";
import { escapeXml, formatNumber, safeColor, truncateText } from "@/server/cards/card-utils";
import type { PinnedOptions, PinnedRepositoriesCardData } from "./pinned.types";

export function renderPinnedCard(data: PinnedRepositoriesCardData, options: PinnedOptions) {
  const { theme } = resolveTheme(options.theme); const width=options.width; const columns=width<560?1:options.columns; const rows=Math.max(1,Math.ceil(data.repositories.length/columns)); const itemWidth=(width-48-(columns-1)*12)/columns; const itemHeight=options.showDescription?112:86; const height=76+rows*(itemHeight+12);
  let content=`<text x="24" y="31" class="title" font-size="16">Pinned Repositories</text><text x="24" y="50" class="muted" font-size="10">@${escapeXml(data.username)}</text>`;
  if(!data.repositories.length)content+=`<text x="24" y="96" class="muted" font-size="11">No public pinned repositories</text>`;
  content+=data.repositories.map((repository,index)=>{const column=index%columns,row=Math.floor(index/columns),x=24+column*(itemWidth+12),y=68+row*(itemHeight+12);return `<rect x="${x}" y="${y}" width="${itemWidth}" height="${itemHeight}" rx="10" fill="${theme.progressBackground}"/><text x="${x+14}" y="${y+23}" class="title" font-size="11">${escapeXml(truncateText(repository.name,columns===2?22:42))}</text>${repository.isArchived?`<text x="${x+itemWidth-12}" y="${y+23}" text-anchor="end" class="muted" font-size="7">ARCHIVED</text>`:""}${options.showDescription?`<text x="${x+14}" y="${y+47}" class="muted" font-size="9">${escapeXml(truncateText(repository.description??"No description",columns===2?38:70))}</text>`:""}${options.showLanguage&&repository.primaryLanguage?`<circle cx="${x+18}" cy="${y+itemHeight-18}" r="4" fill="${safeColor(repository.primaryLanguage.color)}"/><text x="${x+28}" y="${y+itemHeight-14}" class="muted" font-size="8">${escapeXml(truncateText(repository.primaryLanguage.name,12))}</text>`:""}${options.showStars?`<text x="${x+itemWidth-74}" y="${y+itemHeight-14}" class="muted" font-size="8">★ ${formatNumber(repository.stars,options.locale)}</text>`:""}${options.showForks?`<text x="${x+itemWidth-34}" y="${y+itemHeight-14}" class="muted" font-size="8">⑂ ${formatNumber(repository.forks,options.locale)}</text>`:""}`}).join("");
  return svgDocument({width,height,theme,hideBorder:options.hideBorder,title:`${data.username}'s pinned repositories`,description:`${data.repositories.length} public pinned repositories`,content});
}
