"use client";
/* eslint-disable @next/next/no-img-element */
import{useDeferredValue,useEffect,useMemo,useState}from"react";import{AlertCircle,Code2,LoaderCircle,RotateCcw}from"lucide-react";import{Button}from"@/components/ui/button";import{CopyButton}from"@/components/ui/copy-button";import{Input,Select}from"@/components/ui/primitives";import{Switch}from"@/components/ui/switch";
type CardType="overview"|"languages"|"contributions"|"streak";type OutputFormat="Markdown"|"HTML"|"Direct URL";
const hiddenOptions=[["followers","Followers"],["forks","Forks"],["stars","Stars"],["commits","Commits"],["pull_requests","Pull requests"],["languages","Languages"]]as const;
export function Playground(){
 const[type,setType]=useState<CardType>("overview"),[username,setUsername]=useState("dimitrisnimas"),[debouncedUsername,setDebouncedUsername]=useState(username),[theme,setTheme]=useState("midnight"),[width,setWidth]=useState(520),[showAvatar,setShowAvatar]=useState(true),[showIcons,setShowIcons]=useState(true),[showBorder,setShowBorder]=useState(true),[hidden,setHidden]=useState<string[]>([]),[layout,setLayout]=useState("default"),[langsCount,setLangsCount]=useState(5),[exclude,setExclude]=useState(""),[debouncedExclude,setDebouncedExclude]=useState(""),[hideProgress,setHideProgress]=useState(false),[year,setYear]=useState(new Date().getUTCFullYear()),[showTotal,setShowTotal]=useState(true),[showLegend,setShowLegend]=useState(true),[showWeekdays,setShowWeekdays]=useState(true),[showRing,setShowRing]=useState(true),[format,setFormat]=useState<OutputFormat>("Markdown"),[loadedUrl,setLoadedUrl]=useState(""),[errorUrl,setErrorUrl]=useState(""),[refreshKey,setRefreshKey]=useState(0);const deferredWidth=useDeferredValue(width);
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedUsername(username.trim()),500);return()=>window.clearTimeout(timer)},[username]);useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedExclude(exclude.trim()),500);return()=>window.clearTimeout(timer)},[exclude]);
 const query=useMemo(()=>{const safeWidth=type==="contributions"?Math.max(500,deferredWidth):deferredWidth;const p=new URLSearchParams({username:debouncedUsername||"dimitrisnimas",theme,width:String(safeWidth),hide_border:String(!showBorder)});if(type==="overview"){p.set("show_avatar",String(showAvatar));p.set("show_icons",String(showIcons));if(hidden.length)p.set("hide",[...hidden].sort().join(","));}if(type==="languages"){p.set("layout",layout);p.set("langs_count",String(langsCount));p.set("hide_progress",String(hideProgress));if(debouncedExclude)p.set("exclude",debouncedExclude);}if(type==="contributions"){p.set("year",String(year));p.set("show_total",String(showTotal));p.set("show_legend",String(showLegend));p.set("show_weekdays",String(showWeekdays));}if(type==="streak"){p.set("year",String(year));p.set("show_ring",String(showRing));}return p.toString()},[type,debouncedUsername,theme,deferredWidth,showBorder,showAvatar,showIcons,hidden,layout,langsCount,hideProgress,debouncedExclude,year,showTotal,showLegend,showWeekdays,showRing]);
 const previewUrl=`/api/cards/${type}?${query}${refreshKey?`&refresh=${refreshKey}`:""}`,publicUrl=`${process.env.NEXT_PUBLIC_APP_URL??"https://repopulse.kubik.gr"}/api/cards/${type}?${query}`,outputs:Record<OutputFormat,string>={Markdown:`![RepoPulse ${title(type)}](${publicUrl})`,HTML:`<img src="${publicUrl}" alt="RepoPulse ${title(type)}" />`,"Direct URL":publicUrl},previewState=errorUrl===previewUrl?"error":loadedUrl===previewUrl?"ready":"loading";
 function reset(){setUsername("dimitrisnimas");setTheme("midnight");setWidth(520);setShowAvatar(true);setShowIcons(true);setShowBorder(true);setHidden([]);setLayout("default");setLangsCount(5);setExclude("");setHideProgress(false);setYear(new Date().getUTCFullYear());setShowTotal(true);setShowLegend(true);setShowWeekdays(true);setShowRing(true)}
 return <div className="grid min-h-[calc(100vh-65px)] lg:grid-cols-[380px_1fr]"><aside className="border-r border-white/[.08] p-5 lg:p-7"><div className="flex items-center justify-between"><div><p className="text-xs text-violet-300">CONFIGURATION</p><h1 className="mt-2 text-xl font-semibold">{title(type)}</h1></div><Button variant="ghost" aria-label="Reset settings" onClick={reset}><RotateCcw size={15}/></Button></div><div className="mt-8 space-y-6">
 <Field label="GitHub username"><Input value={username} onChange={(e)=>setUsername(e.target.value)} maxLength={39}/></Field><Field label="Card type"><Select value={type} onChange={(e)=>setType(e.target.value as CardType)}><option value="overview">Overview</option><option value="languages">Languages</option><option value="contributions">Contributions</option><option value="streak">Streak</option></Select></Field><Field label="Theme"><Select value={theme} onChange={(e)=>setTheme(e.target.value)}>{["dark","light","github-dark","github-light","midnight"].map((item)=><option key={item}>{item}</option>)}</Select></Field>
 {type==="overview"&&<><Toggle label="Show avatar" value={showAvatar} setValue={setShowAvatar}/><Toggle label="Show icons" value={showIcons} setValue={setShowIcons}/><fieldset><legend className="mb-3 text-xs text-zinc-500">Hide metrics</legend><div className="grid grid-cols-2 gap-2">{hiddenOptions.map(([key,label])=><Check key={key} label={label} checked={hidden.includes(key)} onChange={()=>setHidden((c)=>c.includes(key)?c.filter((i)=>i!==key):[...c,key])}/>)}</div></fieldset></>}
 {type==="languages"&&<><Field label="Layout"><Select value={layout} onChange={(e)=>setLayout(e.target.value)}><option value="default">Default</option><option value="compact">Compact</option><option value="donut">Donut</option></Select></Field><Field label="Languages count"><Input type="number" min={1} max={10} value={langsCount} onChange={(e)=>setLangsCount(Math.max(1,Math.min(10,Number(e.target.value))))}/></Field><Field label="Exclude languages"><Input value={exclude} onChange={(e)=>setExclude(e.target.value)} placeholder="html, css"/></Field><Toggle label="Hide progress bars" value={hideProgress} setValue={setHideProgress}/></>}
 {(type==="contributions"||type==="streak")&&<Field label="Year"><Input type="number" min={2008} max={new Date().getUTCFullYear()} value={year} onChange={(e)=>setYear(Number(e.target.value))}/></Field>}
 {type==="contributions"&&<><Toggle label="Show total" value={showTotal} setValue={setShowTotal}/><Toggle label="Show legend" value={showLegend} setValue={setShowLegend}/><Toggle label="Show weekdays" value={showWeekdays} setValue={setShowWeekdays}/></>}
 {type==="streak"&&<Toggle label="Show ring" value={showRing} setValue={setShowRing}/>}<Toggle label="Show border" value={showBorder} setValue={setShowBorder}/><Field label="Width"><Input type="number" value={width} min={type==="contributions"?500:320} max={type==="contributions"?1000:900} onChange={(e)=>setWidth(Number(e.target.value)||520)}/></Field></div></aside>
 <main className="bg-[radial-gradient(circle_at_50%_20%,rgba(124,58,237,.08),transparent_40%)] p-5 lg:p-10"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><div><p className="text-xs text-zinc-600">LIVE PREVIEW</p><p className="mt-1 text-sm text-zinc-400">Live public GitHub data</p></div><Button variant="secondary" onClick={()=>setRefreshKey(Date.now())}><RotateCcw size={14}/> Refresh</Button></div><div className="relative mt-8 grid min-h-96 place-items-center overflow-auto rounded-2xl border border-dashed border-white/10 bg-black/20 p-6">{previewState==="loading"&&<div className="absolute inset-0 z-10 grid place-items-center bg-black/55 text-sm text-zinc-500"><div><LoaderCircle className="mx-auto mb-3 animate-spin"/>Fetching GitHub data...</div></div>}{previewState==="error"&&<div className="text-center text-sm text-zinc-500"><AlertCircle className="mx-auto mb-3 text-red-300"/>The preview could not be loaded.</div>}<img key={previewUrl} src={previewUrl} alt={`GitHub ${type} card for ${debouncedUsername}`} onLoad={()=>setLoadedUrl(previewUrl)} onError={()=>setErrorUrl(previewUrl)} className={previewState==="error"?"hidden":"max-w-none"}/></div>
 <div className="mt-8"><div className="flex items-center justify-between"><div className="flex gap-1 rounded-lg border border-white/10 bg-black/30 p-1">{(["Markdown","HTML","Direct URL"]as OutputFormat[]).map((item)=><button key={item} onClick={()=>setFormat(item)} className={`rounded-md px-3 py-1.5 text-xs ${format===item?"bg-white/10 text-white":"text-zinc-500"}`}>{item}</button>)}</div><span className="hidden items-center gap-2 text-xs text-zinc-600 sm:flex"><Code2 size={13}/>Ready to embed</span></div><div className="mt-3 flex items-center gap-3 rounded-xl border border-white/10 bg-black/40 p-3"><code className="min-w-0 flex-1 overflow-x-auto whitespace-nowrap text-xs text-violet-200">{outputs[format]}</code><CopyButton value={outputs[format]}/></div></div></div></main></div>
}
function title(type:CardType){return({overview:"Overview card",languages:"Languages card",contributions:"Contribution calendar",streak:"Contribution streak"})[type]}function Field({label,children}:{label:string;children:React.ReactNode}){return<label className="block"><span className="mb-2 block text-xs font-medium text-zinc-500">{label}</span>{children}</label>}function Toggle({label,value,setValue}:{label:string;value:boolean;setValue:(value:boolean)=>void}){return<div className="flex items-center justify-between"><span className="text-sm text-zinc-400">{label}</span><Switch checked={value} onChange={setValue} label={label}/></div>}function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:()=>void}){return<label className="flex cursor-pointer items-center gap-2 rounded-lg border border-white/[.07] px-3 py-2 text-xs text-zinc-500"><input type="checkbox" checked={checked} onChange={onChange} className="accent-violet-500"/>{label}</label>}
