import { z } from "zod";

const schema = z.object({
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  APP_VERSION: z.string().default("0.4.0"),
  GITHUB_TOKEN: z.string().min(1).optional(),
  REPOPULSE_PRIVATE_GITHUB_TOKEN: z.string().min(1).optional(),
  REPOPULSE_PRIVATE_REPOSITORIES: z.string().max(1200).optional(),
  UPSTASH_REDIS_REST_URL: z.string().url().optional(),
  UPSTASH_REDIS_REST_TOKEN: z.string().min(1).optional(),
  CRON_SECRET: z.string().min(16).optional(),
  REPOPULSE_CACHE_TTL_SECONDS: z.coerce.number().int().positive().default(3600),
  REPOPULSE_STALE_TTL_SECONDS: z.coerce.number().int().positive().default(86400),
  REPOPULSE_RATE_LIMIT_REQUESTS: z.coerce.number().int().positive().default(60),
  REPOPULSE_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(60),
  REPOPULSE_GITHUB_TIMEOUT_MS: z.coerce.number().int().min(1000).max(30000).default(6000),
  REPOPULSE_GITHUB_MAX_RETRIES: z.coerce.number().int().min(0).max(4).default(2),
  REPOPULSE_GITHUB_RETRY_BASE_DELAY_MS: z.coerce.number().int().min(50).max(2000).default(250),
  REPOPULSE_CIRCUIT_FAILURE_THRESHOLD: z.coerce.number().int().min(2).max(20).default(5),
  REPOPULSE_CIRCUIT_COOLDOWN_SECONDS: z.coerce.number().int().min(5).max(600).default(60),
  REPOPULSE_DISTRIBUTED_LOCK_TTL_SECONDS: z.coerce.number().int().min(5).max(60).default(15),
  REPOPULSE_DEDUPLICATION_WAIT_MS: z.coerce.number().int().min(100).max(5000).default(1500),
  REPOPULSE_REFRESH_MAX_ENTRIES: z.coerce.number().int().min(1).max(100).default(25),
});

export const env = schema.parse({
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  APP_VERSION: process.env.APP_VERSION,
  GITHUB_TOKEN: process.env.GITHUB_TOKEN || undefined,
  REPOPULSE_PRIVATE_GITHUB_TOKEN: process.env.REPOPULSE_PRIVATE_GITHUB_TOKEN || undefined,
  REPOPULSE_PRIVATE_REPOSITORIES: process.env.REPOPULSE_PRIVATE_REPOSITORIES || undefined,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL || undefined,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN || undefined,
  CRON_SECRET: process.env.CRON_SECRET || undefined,
  REPOPULSE_CACHE_TTL_SECONDS: process.env.REPOPULSE_CACHE_TTL_SECONDS,
  REPOPULSE_STALE_TTL_SECONDS: process.env.REPOPULSE_STALE_TTL_SECONDS,
  REPOPULSE_RATE_LIMIT_REQUESTS: process.env.REPOPULSE_RATE_LIMIT_REQUESTS,
  REPOPULSE_RATE_LIMIT_WINDOW_SECONDS: process.env.REPOPULSE_RATE_LIMIT_WINDOW_SECONDS,
  REPOPULSE_GITHUB_TIMEOUT_MS: process.env.REPOPULSE_GITHUB_TIMEOUT_MS,
  REPOPULSE_GITHUB_MAX_RETRIES: process.env.REPOPULSE_GITHUB_MAX_RETRIES,
  REPOPULSE_GITHUB_RETRY_BASE_DELAY_MS: process.env.REPOPULSE_GITHUB_RETRY_BASE_DELAY_MS,
  REPOPULSE_CIRCUIT_FAILURE_THRESHOLD: process.env.REPOPULSE_CIRCUIT_FAILURE_THRESHOLD,
  REPOPULSE_CIRCUIT_COOLDOWN_SECONDS: process.env.REPOPULSE_CIRCUIT_COOLDOWN_SECONDS,
  REPOPULSE_DISTRIBUTED_LOCK_TTL_SECONDS: process.env.REPOPULSE_DISTRIBUTED_LOCK_TTL_SECONDS,
  REPOPULSE_DEDUPLICATION_WAIT_MS: process.env.REPOPULSE_DEDUPLICATION_WAIT_MS,
  REPOPULSE_REFRESH_MAX_ENTRIES: process.env.REPOPULSE_REFRESH_MAX_ENTRIES,
});
