import { ArrowRight, Braces, Gauge, LockKeyhole, Palette, Server, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { StatsCard } from "@/components/marketing/stats-card";
import { Badge, Card } from "@/components/ui/primitives";
import { Button } from "@/components/ui/button";

const benefits = [
  [Zap, "Fast by default", "Edge-ready delivery and a cache-first architecture keep every profile feeling instant."],
  [ShieldCheck, "Built for uptime", "A dependable private-source foundation without fragile community instances."],
  [Palette, "Yours, pixel-perfect", "Themes, dimensions, details, and display options designed to fit your README."],
];
const types = ["Profile stats", "Top languages", "Contribution streak", "Repository card", "Contribution graph", "Wakatime"];

export default function Home() {
  return <><section className="relative overflow-hidden border-b border-white/[0.07]"><div className="grid-bg absolute inset-0" /><div className="absolute left-1/2 top-0 h-96 w-96 -translate-x-1/2 rounded-full bg-violet-600/10 blur-3xl" /><div className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-16 px-5 py-24 lg:grid-cols-[1.05fr_.95fr] lg:px-8"><div><Badge><Sparkles size={12} className="mr-1.5" /> Private preview</Badge><h1 className="text-gradient mt-7 max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-6xl lg:text-7xl">Beautiful GitHub metrics. Built to stay online.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-400">Generate fast, customizable, and reliable GitHub profile cards without depending on unstable public instances.</p><div className="mt-9 flex flex-wrap gap-3"><Button href="/playground">Open Playground <ArrowRight size={16} /></Button><Button href="/docs" variant="secondary">View Documentation</Button></div><div className="mt-10 flex flex-wrap gap-5 text-xs text-zinc-600"><span>Zero setup</span><span>•</span><span>README-ready</span><span>•</span><span>Developer first</span></div></div><div className="glow relative"><div className="mb-3 flex items-center gap-1.5 pl-2 text-[11px] text-zinc-600"><span className="size-2 rounded-full bg-red-400/60" /><span className="size-2 rounded-full bg-amber-400/60" /><span className="size-2 rounded-full bg-emerald-400/60" /><span className="ml-2 font-mono">repopulse.kubik.gr/api/card</span></div><StatsCard /></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-28 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-medium text-violet-300">Engineered differently</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl">Metrics you can actually depend on.</h2><p className="mt-5 text-zinc-500">Clean design on the surface. Production-grade thinking underneath.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3">{benefits.map(([Icon, title, copy]) => { const I = Icon as typeof Zap; return <Card key={String(title)} className="p-6"><span className="grid size-10 place-items-center rounded-xl border border-violet-400/20 bg-violet-400/10 text-violet-300"><I size={18} /></span><h3 className="mt-8 font-medium">{title as string}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{copy as string}</p></Card>; })}</div></section>
  <section className="border-y border-white/[0.07] bg-white/[0.015]"><div className="mx-auto max-w-7xl px-5 py-28 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm text-violet-300">One endpoint. Every insight.</p><h2 className="mt-4 text-3xl font-semibold tracking-tight">Cards for every kind of builder.</h2></div><Button href="/docs/cards" variant="ghost">Explore card types <ArrowRight size={15} /></Button></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{types.map((type, index) => <div key={type} className="bg-[#09090b] p-6"><div className="flex items-center gap-3"><span className="font-mono text-xs text-zinc-700">0{index + 1}</span><span className="text-sm">{type}</span></div><div className="mt-7 h-1.5 overflow-hidden rounded-full bg-white/[0.04]"><div className="h-full rounded-full bg-gradient-to-r from-violet-600/60 to-violet-300/60" style={{ width: `${42 + index * 8}%` }} /></div></div>)}</div></div></section>
  <section className="mx-auto grid max-w-7xl gap-16 px-5 py-28 lg:grid-cols-2 lg:px-8"><div className="self-center"><Badge>Infrastructure</Badge><h2 className="mt-6 text-3xl font-semibold tracking-tight sm:text-4xl">Reliability isn&apos;t a feature. It&apos;s the foundation.</h2><p className="mt-5 max-w-lg leading-7 text-zinc-500">RepoPulse is designed around predictable performance, careful caching, and clear operational visibility from day one.</p><div className="mt-9 space-y-5">{[[Server,"Edge-ready architecture"],[Gauge,"Fast, observable requests"],[LockKeyhole,"Privacy-conscious by design"]].map(([Icon, label]) => { const I = Icon as typeof Server; return <div key={String(label)} className="flex items-center gap-3 text-sm text-zinc-300"><I size={17} className="text-violet-300" />{label as string}</div>; })}</div></div><Card className="relative overflow-hidden p-8"><div className="absolute right-0 top-0 size-40 bg-violet-500/10 blur-3xl" /><p className="font-mono text-xs text-zinc-600">SYSTEM STATUS</p><div className="mt-8 flex items-end justify-between"><div><p className="text-4xl font-semibold">99.99%</p><p className="mt-2 text-sm text-zinc-500">Target uptime</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">All systems operational</span></div><div className="mt-10 grid grid-cols-24 gap-1">{Array.from({length:48}).map((_,i) => <span key={i} className={`h-16 rounded-sm ${i === 31 ? "bg-emerald-400/40" : "bg-emerald-400/70"}`} />)}</div></Card></section>
  <section className="border-t border-white/[0.07]"><div className="mx-auto max-w-7xl px-5 py-28 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm text-violet-300">Make it yours</p><h2 className="mt-4 text-3xl font-semibold">Designed to belong in your README.</h2><p className="mt-5 max-w-xl text-zinc-500">Tune the theme, icons, borders, width, and motion. Your profile, your signal.</p></div><div className="grid grid-cols-2 gap-3">{[["12+","curated themes"],["6","card formats"],["∞","custom widths"],["1","simple URL"]].map(([value,label]) => <Card key={label} className="p-5"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-zinc-500">{label}</p></Card>)}</div></div></div></section>
  <section className="mx-auto max-w-7xl px-5 pb-28 lg:px-8"><div className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-white/[.06] to-violet-500/[.05] px-6 py-16 text-center sm:px-12"><Braces className="mx-auto text-violet-300" /><h2 className="mt-6 text-3xl font-semibold tracking-tight sm:text-4xl">Your README deserves better metrics.</h2><p className="mx-auto mt-4 max-w-xl text-zinc-500">Start shaping a card that matches your work. The playground is ready.</p><div className="mt-8 flex justify-center gap-3"><Button href="/playground">Build your card <ArrowRight size={16} /></Button><Button href="/docs" variant="secondary">Read the docs</Button></div></div></section></>;
}
