import { describe, expect, it } from "vitest";
import { renderPrivateActivityCard } from "./private-activity-card";
import { privateRepositoryDescriptions, selectedPrivateRepositories } from "./private-activity-service";
describe("private activity card",()=>{
  it("accepts only Dimitris' explicitly selected repositories",()=>{expect(selectedPrivateRepositories("dimitrisnimas/one, two\n'three';dimitrisnimas/one")).toEqual(["one","two","three"]);for(const value of["someone/repo","dimitrisnimas/../secret","dimitrisnimas/repo/extra","https://github.com/dimitrisnimas/repo"])expect(()=>selectedPrivateRepositories(value)).toThrow()});
  it("parses bounded public descriptions without treating colons in text as separators",()=>{const descriptions=privateRepositoryDescriptions("ecos.identity:Authentication in .NET & account management in TypeScript|ecos.nexus:Connects services: APIs and workflows");expect(descriptions.get("ecos.identity")).toContain("Authentication");expect(descriptions.get("ecos.nexus")).toBe("Connects services: APIs and workflows");expect(()=>privateRepositoryDescriptions(`repo:${"x".repeat(121)}`)).toThrow()});
  it("renders aggregate metadata and escapes private repository names",()=>{const svg=renderPrivateActivityCard({username:"dimitrisnimas",about:"Building private products & reliable APIs.",repositories:[{name:"private<app>",description:"Authentication & account management",language:"TypeScript",languageColor:"#3178c6",totalCommits:140,lastCommitAt:"2026-08-01T12:00:00Z"}],unavailable:0,generatedAt:"2026-08-02T00:00:00Z"},{theme:"dark",width:680,hideBorder:false,locale:"en"});expect(svg).toContain("private&lt;app&gt;");expect(svg).toContain("Authentication &amp; account management");expect(svg).toContain("Building private products &amp; reliable APIs.");expect(svg).toContain("140 commits");expect(svg).toContain("repositories");expect(svg).toContain("Built with");expect(svg).toContain("RepoPulse logo");expect(svg).toContain(">REPO</text>");expect(svg).toContain(">PULSE</text>");expect(svg).not.toContain("<image");expect(svg).not.toContain("Metadata only");expect(svg).not.toContain("more private repositories");expect(svg).not.toContain("private<app>");expect(svg).not.toContain("<script")});
  it("reports partial repository failures without leaking their names",()=>{const svg=renderPrivateActivityCard({username:"dimitrisnimas",about:"Private work.",repositories:[],unavailable:2,generatedAt:"2026-08-02T00:00:00Z"},{theme:"midnight",width:500,hideBorder:true,locale:"en"});expect(svg).toContain("2 temporarily unavailable")});
});
