import { resolveTheme } from "@/config/themes";
import { svgDocument } from "@/server/cards/card-renderer";
import { escapeXml, formatNumber, safeColor, truncateText } from "@/server/cards/card-utils";
import type { PrivateActivityData, PrivateActivityOptions } from "./private-activity.types";

function wrap(value:string,limit:number,lines=2){const words=value.trim().split(/\s+/);const result:string[]=[];let line="";for(const word of words){if(`${line} ${word}`.trim().length<=limit)line=`${line} ${word}`.trim();else{if(line)result.push(line);line=word;if(result.length===lines-1)break}}if(line&&result.length<lines)result.push(line);const consumed=result.join(" ").length<value.trim().length; if(consumed&&result.length)result[result.length-1]=truncateText(result[result.length-1],Math.max(4,limit));return result}
const logo=`<g aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M25 39h14l6-20 9 40 8-27 6 12h17" stroke="#8b5cf6" stroke-width="3"/><path d="M54 59l8-27 6 12h17" stroke="#22d3ee" stroke-width="3"/></g>`;
const lock=(x:number,y:number)=>`<g transform="translate(${x} ${y})" fill="none" stroke="#a78bfa" stroke-width="1.8"><rect x="1" y="7" width="14" height="12" rx="3"/><path d="M4 7V5a4 4 0 0 1 8 0v2"/></g>`;
const calendar=(x:number,y:number)=>`<g transform="translate(${x} ${y})" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="1" y="3" width="16" height="15" rx="2"/><path d="M1 8h16M5 1v4M13 1v4"/></g>`;
const footerLogo=(x:number,y:number)=>`<g transform="translate(${x} ${y})" aria-label="RepoPulse logo"><path d="M0 9h7l3-8 4 16 4-11 3 5h7" fill="none" stroke="#8b5cf6" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/><text x="35" y="13" fill="#f4f4f5" font-size="11" font-weight="700" letter-spacing=".5">REPO</text><text x="66" y="13" fill="#8b5cf6" font-size="11" font-weight="700" letter-spacing=".5">PULSE</text></g>`;

export function renderPrivateActivityCard(data:PrivateActivityData,options:PrivateActivityOptions){
  const{theme}=resolveTheme(options.theme);const width=options.width;const compact=width<560;const rowHeight=64;const headerHeight=84;const aboutHeight=94;const tableTop=headerHeight+aboutHeight+12;const footerHeight=data.unavailable?32:18;const height=tableTop+Math.max(1,data.repositories.length)*rowHeight+footerHeight+18;const total=data.repositories.reduce((sum,repo)=>sum+repo.totalCommits,0);const aboutLines=wrap(data.about,compact?54:88,2);
  const titleX=compact?76:104;const repoStatX=compact?width-156:width-252;const commitsX=width-28;
  let content=`${logo}<line x1="94" y1="18" x2="94" y2="64" stroke="${theme.border}"/><text x="${titleX}" y="35" class="title" font-size="18">Private Repos Activity</text><text x="${titleX}" y="56" class="muted" font-size="11">@${data.username}</text><text x="${repoStatX}" y="33" class="title" font-size="19">${data.repositories.length}</text><text x="${repoStatX}" y="52" class="muted" font-size="9">repositories</text><text x="${commitsX}" y="33" text-anchor="end" class="title" font-size="19">${escapeXml(formatNumber(total,options.locale))}</text><text x="${commitsX}" y="52" text-anchor="end" class="muted" font-size="9">commits</text>`;
  content+=`<rect x="24" y="${headerHeight}" width="${width-48}" height="${aboutHeight-10}" rx="12" fill="${theme.progressBackground}" stroke="${theme.border}"/><text x="40" y="${headerHeight+25}" class="accent" font-size="9" font-weight="700" letter-spacing="1.2">ABOUT</text>${aboutLines.map((line,index)=>`<text x="40" y="${headerHeight+49+index*19}" class="text" font-size="11">${escapeXml(line)}</text>`).join("")}`;
  if(!data.repositories.length)content+=`<text x="36" y="${tableTop+29}" class="muted" font-size="11">No configured repositories are currently available</text>`;
  content+=data.repositories.map((repo,index)=>{const y=tableTop+index*rowHeight;const date=repo.lastCommitAt?new Intl.DateTimeFormat(options.locale,{year:"numeric",month:"short",day:"2-digit",timeZone:"UTC"}).format(new Date(repo.lastCommitAt)):"No commits";const languageX=compact?Math.round(width*.45):Math.round(width*.47);const countX=compact?width-128:width-178;return `<rect x="24" y="${y}" width="${width-48}" height="${rowHeight}" rx="${index===0?10:0}" fill="${index%2?theme.background:theme.progressBackground}" stroke="${theme.border}"/>${lock(36,y+14)}<text x="62" y="${y+27}" class="title" font-size="11">${escapeXml(truncateText(repo.name,compact?20:30))}</text><text x="62" y="${y+46}" class="muted" font-size="8">${escapeXml(truncateText(repo.description??"Private ecosystem service",compact?38:58))}</text><circle cx="${languageX}" cy="${y+25}" r="4" fill="${safeColor(repo.languageColor,theme.accent)}"/><text x="${languageX+11}" y="${y+29}" class="muted" font-size="9">${escapeXml(truncateText(repo.language??"Other",compact?9:14))}</text><text x="${countX}" y="${y+29}" text-anchor="end" class="text" font-size="10">${escapeXml(formatNumber(repo.totalCommits,options.locale))} commits</text><g color="${theme.muted}">${calendar(width-129,y+16)}</g><text x="${width-36}" y="${y+29}" text-anchor="end" class="muted" font-size="8">${escapeXml(date)}</text>`}).join("");
  const footerY=tableTop+Math.max(1,data.repositories.length)*rowHeight+18;const brandX=width/2-40;content+=`<text x="${brandX-8}" y="${footerY}" text-anchor="end" class="muted" font-size="10">Built with</text>${footerLogo(brandX,footerY-14)}${data.unavailable?`<text x="${width-24}" y="${footerY}" text-anchor="end" class="muted" font-size="8">${data.unavailable} temporarily unavailable</text>`:""}`;
  return svgDocument({width,height,theme,hideBorder:options.hideBorder,title:"Dimitris Nimas private repository activity",description:`Complete activity metadata for ${data.repositories.length} selected private repositories; no source code is read`,content});
}
